# Generated by Django 4.2.20 on 2025-11-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apresentacao_produto', models.TextField(verbose_name='Apresentação do Produto')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_papel', models.CharField(max_length=150, verbose_name='Usuário (Função ou Papel)')),
                ('descricao_usuario', models.TextField(verbose_name='Descrição do Usuário')),
                ('acoes_usuario', models.TextField(help_text='O que o usuário faz dentro do sistema?', verbose_name='Ações do Usuário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da História')),
                ('como', models.CharField(max_length=200, verbose_name='Como (Persona/Usuário)')),
                ('eu_quero', models.CharField(max_length=300, verbose_name='Eu quero (Ação desejada)')),
                ('para_que', models.CharField(max_length=300, verbose_name='Para que (Motivo / Benefício)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='app.produto')),
            ],
        ),
    ]
